/*
 * Copyright 2025 NXP
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef ADC_UTILS_H_
#define ADC_UTILS_H_

/* Include files ------------------------------------------------------------------ */
#include "sdk_project_config.h"
#include "interrupt_manager.h"

/* Macro -------------------------------------------------------------------------- */

typedef struct {
    uint8_t instance; /*Adc instance number*/
    uint8_t chanIndex; /*Adc channel index*/
    adc_chan_config_t *channelConfig; /*generated by peripheral tool */
    const adc_converter_config_t *converterConfig; /*generated by peripheral tool */
    uint16_t adcValue; /*variable to store converted value*/
    bool adcConvDone; /*flag that is set true after conversion*/
    IRQn_Type irqNumber; /*Adc interrupt nummber*/
    isr_t isrHandler; /*pointer to the interrupt handler*/
} adc_instanceConfig_t;

/* Function prototypes ------------------------------------------------------------ */

/* @brief: Initializes the ADC (Analog to Digital Converter) module. */
void v_adcInit(adc_instanceConfig_t *adcInstance);

/* @brief: Scales the latest ADC (Analog to Digital Converter) conversion result proportionally to a user-defined maximum value. */
void v_scaleAdcValue(uint16_t scaleMax, uint16_t *ui16AdcValue);

#endif /* ADC_UTILS_H_ */
